/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestor.alumnos;

import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.Timer;

/**
 *
 * @author samui
 */
public class UIGestorAlumnos extends javax.swing.JFrame {
    private Timer timer;
    public AlumnoDAO gestorAlumnos = new AlumnoDAO();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UIGestorAlumnos.class.getName());

    /**
     * Creates new form UIGestorAlumnos
     */
    public UIGestorAlumnos() {
        initComponents();
        super.setTitle("Gestor de Alumnos - IkerAramburu");
                
        // Placeholders
        ponerPlaceHolder(txtAreaNombre, "Nombre del alumno");
        ponerPlaceHolder(txtAreaPrimerApellido, "Primer apellido del alumno");
        ponerPlaceHolder(txtAreaSegundoApellido, "Segundo apellido del alumno");
        ponerPlaceHolder(txtAreaFecha, "XXXX/XX/XX");
        ponerPlaceHolder(txtAreaClasse, "Classe del alumno");
        
        // Cargamos los alumnos en cuanto se inicia
        cargarAlumnos();
        
        // Al cambiar de panel actualizamos los alumnos
        jTabbedPane1.addChangeListener(e -> cargarAlumnos());
        
        // Monitorizar jList de Updates para modificar
        listAlumnosUpdate.addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            AlumnoDTO alumnoSeleccionado = listAlumnosUpdate.getSelectedValue();

                if (alumnoSeleccionado != null) {
                    textAreaUpdateNombre.setText(alumnoSeleccionado.getNombre());
                    textAreaUpdatePrimerApellido.setText(alumnoSeleccionado.getPrimerApellido());
                    textAreaUpdateSegundoApellido.setText(alumnoSeleccionado.getSegundoApellido());
                    textAreaUpdateFechaNacimiento.setText(alumnoSeleccionado.getFechaNacimiento());
                    textAreaUpdateClasse.setText(alumnoSeleccionado.getClasse());

                }
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaNombre = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaPrimerApellido = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaSegundoApellido = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaFecha = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAreaClasse = new javax.swing.JTextArea();
        buttonInsertarAlumno = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        listAlumnos = new javax.swing.JList<>();
        buttonEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        listAlumnosUpdate = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        textAreaUpdateNombre = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        textAreaUpdatePrimerApellido = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        textAreaUpdateSegundoApellido = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        textAreaUpdateFechaNacimiento = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        textAreaUpdateClasse = new javax.swing.JTextArea();
        buttonActualizar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        txtAreaNombre.setColumns(20);
        txtAreaNombre.setRows(5);
        jScrollPane1.setViewportView(txtAreaNombre);

        txtAreaPrimerApellido.setColumns(20);
        txtAreaPrimerApellido.setRows(5);
        jScrollPane2.setViewportView(txtAreaPrimerApellido);

        jLabel2.setText("1r Apellido:");

        jLabel3.setText("2n Apellido:");

        txtAreaSegundoApellido.setColumns(20);
        txtAreaSegundoApellido.setRows(5);
        jScrollPane3.setViewportView(txtAreaSegundoApellido);

        jLabel4.setText("Fecha de Nacimiento:");

        txtAreaFecha.setColumns(20);
        txtAreaFecha.setRows(5);
        jScrollPane4.setViewportView(txtAreaFecha);

        jLabel5.setText("Classe:");

        txtAreaClasse.setColumns(20);
        txtAreaClasse.setRows(5);
        jScrollPane5.setViewportView(txtAreaClasse);

        buttonInsertarAlumno.setText("Insertar");
        buttonInsertarAlumno.addActionListener(this::buttonInsertarAlumnoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonInsertarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(buttonInsertarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Insertar", jPanel1);

        jScrollPane6.setViewportView(listAlumnos);

        buttonEliminar.setText("Eliminar");
        buttonEliminar.addActionListener(this::buttonEliminarActionPerformed);

        jLabel6.setText("Lista de alumnos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(buttonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel2);

        jScrollPane7.setViewportView(listAlumnosUpdate);

        jLabel7.setText("Nombre");

        textAreaUpdateNombre.setColumns(20);
        textAreaUpdateNombre.setRows(5);
        textAreaUpdateNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane8.setViewportView(textAreaUpdateNombre);

        textAreaUpdatePrimerApellido.setColumns(20);
        textAreaUpdatePrimerApellido.setRows(5);
        jScrollPane9.setViewportView(textAreaUpdatePrimerApellido);

        jLabel8.setText("1r Apellido");

        jLabel9.setText("2n Apellido");

        textAreaUpdateSegundoApellido.setColumns(20);
        textAreaUpdateSegundoApellido.setRows(5);
        jScrollPane10.setViewportView(textAreaUpdateSegundoApellido);

        textAreaUpdateFechaNacimiento.setColumns(20);
        textAreaUpdateFechaNacimiento.setRows(5);
        jScrollPane11.setViewportView(textAreaUpdateFechaNacimiento);

        jLabel10.setText("Fecha de Nacimiento");

        jLabel11.setText("Classe");

        textAreaUpdateClasse.setColumns(20);
        textAreaUpdateClasse.setRows(5);
        jScrollPane12.setViewportView(textAreaUpdateClasse);

        buttonActualizar.setText("Actualizar");
        buttonActualizar.addActionListener(this::buttonActualizarActionPerformed);

        jLabel12.setText("Lista de alumnos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(buttonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(buttonActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modificar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        // Obtenemos el alumno seleccionado
        AlumnoDTO alumnoSeleccionado = listAlumnos.getSelectedValue();

        // Si no hay ningun alumno seleccionado
        if(alumnoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Selecciona un alumno");
            return;
        }

        // Cuadro para confirmar la eliminacion de un alumno
        int confirmacion = JOptionPane.showConfirmDialog(
            this,
            "¿Eliminar a " + alumnoSeleccionado.getNombre() + "?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION
        );

        if(confirmacion == JOptionPane.YES_OPTION) {
            // Eliminamos al alumno
            gestorAlumnos.EliminarAlumno(alumnoSeleccionado.getId());
            // Cargamos la lista de nuevo
            cargarAlumnos();
            JOptionPane.showMessageDialog(this, "Alumno eliminado correctamente");
        }
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void buttonInsertarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertarAlumnoActionPerformed
        // Si hay algun campo vacio mostramos mensaje
        if (txtAreaNombre.getText().isEmpty() || txtAreaPrimerApellido.getText().isEmpty()
            || txtAreaSegundoApellido.getText().isEmpty() || txtAreaFecha.getText().isEmpty()
            || txtAreaClasse.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Rellena todos los campos!");
        }
        // Si la fecha no es valida mostramos mensaje
        else if(!validarFecha(txtAreaFecha.getText())) {
            JOptionPane.showMessageDialog(this, "Formato de fecha no valida! \nEjemplo de formato: 1988/11/10");
        }
        // Insertamos el alumno con los contenidos
        else {
            String nombre = txtAreaNombre.getText();
            String primerApellido = txtAreaPrimerApellido.getText();
            String segundoApellido = txtAreaSegundoApellido.getText();
            String fecha = txtAreaFecha.getText();
            String classe = txtAreaClasse.getText();

            AlumnoDTO alumnoAInsertar = new AlumnoDTO(nombre, primerApellido, segundoApellido, fecha, classe);

            gestorAlumnos.InsertarAlumno(alumnoAInsertar);
            JOptionPane.showMessageDialog(this, "Se ha insertado el alumno en la base de datos!");
        }
    }//GEN-LAST:event_buttonInsertarAlumnoActionPerformed

    private void buttonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActualizarActionPerformed
        String nuevoNombre = textAreaUpdateNombre.getText();
        String nuevoPrimerApellido = textAreaUpdatePrimerApellido.getText();
        String nuevoSegundoApellido = textAreaUpdateSegundoApellido.getText();
        String nuevaFechaNacimiento = textAreaUpdateFechaNacimiento.getText();
        String nuevaClasse = textAreaUpdateClasse.getText();
        int id = listAlumnosUpdate.getSelectedValue().getId();
        
        // Cuadro para confirmar la modificacion de un alumno
        int confirmacion = JOptionPane.showConfirmDialog(
            this,
            "¿Quieres modificar a " + listAlumnosUpdate.getSelectedValue().getNombre() + "?",
            "Confirmar modificación",
            JOptionPane.YES_NO_OPTION
        );

        if(confirmacion == JOptionPane.YES_OPTION) {
            // Modificamos el usuario
            gestorAlumnos.ActualizarAlumno(nuevoNombre, nuevoPrimerApellido, nuevoSegundoApellido, nuevaFechaNacimiento, nuevaClasse, id);
            // Cargamos la lista de nuevo
            cargarAlumnos();
            JOptionPane.showMessageDialog(this, "Alumno modificado correctamente");
        }
    }//GEN-LAST:event_buttonActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UIGestorAlumnos().setVisible(true));
    }
    
    /**
     * Esta función se utiliza para simular un placeholder en un text area
     * 
     * @param textArea text area a utilizar
     * @param placeholder texto que se mostrará
    */
    private void ponerPlaceHolder(JTextArea textArea, String placeholder) {
        // Ponemos el texto pasado al text area
        textArea.setText(placeholder);
        // Cambiamos el color del text area a gris
        textArea.setForeground(Color.GRAY);
        // Creamos un FocusAdapter para monitorear el focus del campo
        textArea.addFocusListener(new FocusAdapter() {
            
            // En caso que se haga focus
            @Override
            public void focusGained(FocusEvent e) {
                // Si el texto es igual al texto del placeholder
                if (textArea.getText().equals(placeholder)) {
                    // Vaciamos el campo
                    textArea.setText("");
                    // Ponemos el texto nuevo de color negro
                    textArea.setForeground(Color.BLACK);
                }
            }
            
            // En caso que se pierda el focus
            @Override
            public void focusLost(FocusEvent e) {
                // Si el campo está vacío
                if (textArea.getText().isEmpty()) {
                    // Ponemos el texto del placeholder
                    textArea.setText(placeholder);
                    // Ponemos el texto de color gris
                    textArea.setForeground(Color.GRAY);
                }
            }
        });
    }
    
    /**
     * Funcion para validar formato de fechas
     * 
     * @param fecha Fecha a validar
     * @return True si es valida, False si no lo es
     */
    private boolean validarFecha(String fecha) {
        // Validar formato XXXX/XX/XX
        if (!fecha.matches("\\d{4}/\\d{2}/\\d{2}")) {
            return false;
        }
        
        // Validar fecha valida
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            sdf.setLenient(false);
            sdf.parse(fecha);
            return true;
        } catch (Exception e) {
            return false;
        }
    }
    
    /**
     * Funcion para cargar la lista de alumnos
     */
    private void cargarAlumnos() {
        // Obtenemos los alumnos en una lista de strings
        ArrayList<AlumnoDTO> listaAlumnos = new ArrayList<>();
        gestorAlumnos.ListarAlumnos(listaAlumnos);
        
        // Creamos una model list y agregamos los alumnos
        DefaultListModel<AlumnoDTO> modeloAlumnos = new DefaultListModel<>();
        for(AlumnoDTO alumno : listaAlumnos) {
            modeloAlumnos.addElement(alumno);
        }
        
        // Asignamos a la lista de alumnos el model creado
        listAlumnos.setModel(modeloAlumnos);
        listAlumnosUpdate.setModel(modeloAlumnos);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonActualizar;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonInsertarAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<AlumnoDTO> listAlumnos;
    private javax.swing.JList<AlumnoDTO> listAlumnosUpdate;
    private javax.swing.JTextArea textAreaUpdateClasse;
    private javax.swing.JTextArea textAreaUpdateFechaNacimiento;
    private javax.swing.JTextArea textAreaUpdateNombre;
    private javax.swing.JTextArea textAreaUpdatePrimerApellido;
    private javax.swing.JTextArea textAreaUpdateSegundoApellido;
    private javax.swing.JTextArea txtAreaClasse;
    private javax.swing.JTextArea txtAreaFecha;
    private javax.swing.JTextArea txtAreaNombre;
    private javax.swing.JTextArea txtAreaPrimerApellido;
    private javax.swing.JTextArea txtAreaSegundoApellido;
    // End of variables declaration//GEN-END:variables
}
